// Offline only: preserve the five approved impulse points and original solver.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { loadTypescript } from '../tests/helpers/load-typescript.mjs';
const load = (name) =>
  loadTypescript(
    new URL(
      '../components/room/physics/pillow/' + name + '.ts',
      import.meta.url,
    ),
  );
const { initializePillowPhysics } = await load('runtime');
const { PillowPhysics } = await load('pillow-physics');
const approved = [
  { id: 1, x: -0.0029092724860163154, z: -0.001877687367043085 },
  { id: 2, x: -0.038336467500059174, z: 0.185070097855176 },
  { id: 5, x: 0.12450004810629874, z: -0.029510946763822155 },
  { id: 6, x: -0.005051744151547863, z: -0.12110260184683876 },
  { id: 7, x: -0.1244365996581678, z: 0.03616429078966527 },
];
await initializePillowPhysics();
const clips = approved.map((impulse) => {
  const sim = new PillowPhysics();
  const frames = [0, 0, 0, 0, 1]; // lift, quaternion x/y/z/w; local rest pose
  try {
    sim.applyImpulse(0, impulse);
    for (let i = 0; i < 1200; i++) {
      sim.step(1 / 120);
      const q = sim.rotation(0);
      frames.push(sim.displacement(0), q.x, q.y, q.z, q.w);
      if (sim.bodies[0].isSleeping()) break;
    }
    assert.ok(sim.bodies[0].isSleeping(), 'Motion must finish at rest');
    return { id: impulse.id, impulse: { x: impulse.x, z: impulse.z }, frames };
  } finally {
    sim.dispose();
  }
});
const source =
  '// Generated by tooling/bake-pillow.mjs. Do not edit.\nexport const BAKED_PILLOW_FPS = 120;\nexport const BAKED_PILLOW_CLIPS = ' +
  JSON.stringify(clips) +
  ';\n';
const target = new URL(
  '../components/room/physics/pillow/baked-data.ts',
  import.meta.url,
);
if (process.argv.includes('--check'))
  assert.equal(fs.readFileSync(target, 'utf8'), source);
else fs.writeFileSync(target, source);
console.log(
  clips.map((c) => ({
    id: c.id,
    frames: c.frames.length / 5,
    seconds: (c.frames.length / 5 - 1) / 120,
  })),
);
